### ISSUE TITLE
Chapter 3: Community Manager

### ISSUE THREAD

**Issue by TheTieflingRngr** [KerygmaDigital/volunteer-handbook#5]

**Comment by TheTieflingRngr** [comment]
@SeraphimRP @crazyweazel feedback is welcome on the text.

**Comment by RdrSeraphim** [comment]
It looks good to me. In terms of content, the only thing I'm uncertain is that enabling Developer Mode used to be required for copying user IDs. Is this not the case anymore or does this tidbit need to be added in that section?

**Comment by TheTieflingRngr** [comment]
> It looks good to me. In terms of content, the only thing I'm uncertain is that enabling Developer Mode used to be required for copying user IDs. Is this not the case anymore or does this tidbit need to be added in that section?

I composed a clause for it. I'll push it later this week, because my internet is kind of meh here and I'm almost out of data.

**Comment by TheTieflingRngr** [comment]
> > It looks good to me. In terms of content, the only thing I'm uncertain is that enabling Developer Mode used to be required for copying user IDs. Is this not the case anymore or does this tidbit need to be added in that section?
> 
> I composed a clause for it. I'll push it later this week, because my internet is kind of meh here and I'm almost out of data.

Composed in, chapter should be about done. Any further feedback @SeraphimRP @crazyweazel?

**Comment by RdrSeraphim** [comment]
I've got nothing to note.

**Comment by TheTieflingRngr** [comment]
> I've got nothing to note.

I’ll await feedback from @crazyweazel before closing the issue.

**Comment by TheTieflingRngr** [comment]
This is the new chapter 2
